name: shop_app

description: A new Flutter project.

publish_to: "none"

version: 0.1.0

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: IranSans
      fonts:
        # - asset: assets/fonts/IRANSans_FaNum_UltraLight.ttf
        # weight: 200
        - asset: assets/fonts/IRANSans(FaNum)_Light.ttf
          weight: 300
        - asset: assets/fonts/IRANSans(FaNum).ttf
          weight: 400
        - asset: assets/fonts/IRANSans(FaNum)_Medium.ttf
          weight: 500
        - asset: assets/fonts/IRANSans(FaNum)_Bold.ttf
          weight: 700
        # - asset: assets/fonts/IRANSans_FaNum_Black.ttf
        # weight: 800
    - family: BYekan
      fonts:
        - asset:  assets/fonts/Yekan.ttf
    - family: AGhasem
      fonts:
        - asset: assets/fonts/AGhasem.ttf
  assets:
    - assets/logos/
    - assets/imgs/products/
    - assets/imgs/vectors/
    - assets/icons/
