name: shop_app_optional_auth

description: Shop App including Authentication strategies.

publish_to: "none"

version: 0.1.0+1000

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  go_router: ^12.1.1
  responsive_framework: ^1.1.0
  carousel_slider: ^4.2.1
  overlay_support: ^2.1.0
  universal_io: ^2.2.2
  persian_number_utility: ^1.1.3
  flutter_multi_formatter: ^2.11.11
  package_info_plus: ^4.2.0
  device_info_plus: ^9.0.3
  url_launcher: ^6.1.14
  geolocator: ^10.1.0
  pin_code_fields: ^8.0.1
  animations: ^2.0.8
  dio: ^5.3.3
  pretty_dio_logger: ^1.3.1
  hive: ^2.2.3
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/logos/
    - assets/imgs/products/
    - assets/imgs/vectors/
    - assets/imgs/banners/
  fonts:
    - family: IranSans
      fonts:
        - asset: assets/fonts/IRANSans(FaNum)_Light.ttf
          weight: 300
        - asset: assets/fonts/IRANSans(FaNum).ttf
          weight: 400
        - asset: assets/fonts/IRANSans(FaNum)_Medium.ttf
          weight: 500
        - asset: assets/fonts/IRANSans(FaNum)_Bold.ttf
          weight: 700
    - family: BYekan
      fonts:
        - asset: assets/fonts/Yekan.ttf
